// Generated by scripts/generate_site_areas.py — do not edit by hand.
// Source: mounting-area SVGs (one closed path per site, in the same
// viewBox as the matching body silhouette). Rear file names are
// left/right swapped relative to the wearer; the generator remaps them.
import CoreGraphics

struct SiteArea: Hashable {
    let viewBoxWidth: CGFloat
    let viewBoxHeight: CGFloat
    let pathData: String
}

enum SiteAreaCatalog {
    static func area(for siteID: String, bodyType: BodyType) -> SiteArea? {
        areas[bodyType.rawValue]?[siteID]
    }

    static let areas: [String: [String: SiteArea]] = [
        "woman": [
            "abdomen-left": SiteArea(viewBoxWidth: 400, viewBoxHeight: 999, pathData: "M 255 339 C 261 343 264 353 265 365 C 267 380 268 391 274 405 C 279 416 282 427 279 437 C 270 445 256 447 243 442 C 229 438 222 429 220 415 C 218 396 221 376 228 357 C 235 343 246 334 255 339 Z"),
            "abdomen-right": SiteArea(viewBoxWidth: 400, viewBoxHeight: 999, pathData: "M 145 339 C 139 343 136 353 135 365 C 133 380 132 391 126 405 C 121 416 118 427 121 437 C 130 445 144 447 157 442 C 171 438 178 429 180 415 C 182 396 179 376 172 357 C 165 343 154 334 145 339 Z"),
            "back-upper-arm-left": SiteArea(viewBoxWidth: 399, viewBoxHeight: 1000, pathData: "M 91 230 C 87 240 86 255 86 270 C 86 284 84 297 81 309 C 84 319 90 323 98 320 C 105 308 109 294 112 278 C 114 260 112 244 108 232 C 103 226 96 227 91 230 Z"),
            "back-upper-arm-right": SiteArea(viewBoxWidth: 399, viewBoxHeight: 1000, pathData: "M 308 230 C 312 240 313 255 313 270 C 313 284 315 297 318 309 C 315 319 309 323 301 320 C 294 308 290 294 287 278 C 285 260 287 244 291 232 C 296 226 303 227 308 230 Z"),
            "front-thigh-left": SiteArea(viewBoxWidth: 400, viewBoxHeight: 999, pathData: "M 287 548 C 290 560 288 576 284 591 C 280 606 275 619 268 627 C 259 631 249 628 243 620 C 241 608 244 598 243 586 C 242 573 238 559 241 549 C 253 541 277 541 287 548 Z"),
            "front-thigh-right": SiteArea(viewBoxWidth: 400, viewBoxHeight: 999, pathData: "M 113 548 C 110 560 112 576 116 591 C 120 606 125 619 132 627 C 141 631 151 628 157 620 C 159 608 156 598 157 586 C 158 573 162 559 159 549 C 147 541 123 541 113 548 Z"),
            "lower-back-left": SiteArea(viewBoxWidth: 399, viewBoxHeight: 1000, pathData: "M 149 374 C 138 375 128 380 124 388 C 124 397 131 403 143 406 C 158 411 174 412 184 407 C 191 402 192 395 187 388 C 177 379 161 373 149 374 Z"),
            "lower-back-right": SiteArea(viewBoxWidth: 399, viewBoxHeight: 1000, pathData: "M 250 374 C 261 375 271 380 275 388 C 275 397 268 403 256 406 C 241 411 225 412 215 407 C 208 402 207 395 212 388 C 222 379 238 373 250 374 Z"),
            "outer-thigh-left": SiteArea(viewBoxWidth: 399, viewBoxHeight: 1000, pathData: "M 116 555 C 114 566 115 580 118 594 C 121 609 125 621 131 627 C 139 629 145 624 148 615 C 148 603 146 594 148 583 C 150 571 153 559 150 551 C 140 546 123 548 116 555 Z"),
            "outer-thigh-right": SiteArea(viewBoxWidth: 399, viewBoxHeight: 1000, pathData: "M 283 555 C 285 566 284 580 281 594 C 278 609 274 621 268 627 C 260 629 254 624 251 615 C 251 603 253 594 251 583 C 249 571 246 559 249 551 C 259 546 276 548 283 555 Z"),
            "upper-buttock-left": SiteArea(viewBoxWidth: 399, viewBoxHeight: 1000, pathData: "M 133 447 C 125 451 119 461 115 473 C 111 486 110 498 114 505 C 122 508 131 503 139 494 C 149 483 157 470 159 458 C 158 448 143 443 133 447 Z"),
            "upper-buttock-right": SiteArea(viewBoxWidth: 399, viewBoxHeight: 1000, pathData: "M 266 447 C 274 451 280 461 284 473 C 288 486 289 498 285 505 C 277 508 268 503 260 494 C 250 483 242 470 240 458 C 241 448 256 443 266 447 Z"),
        ],
    ]
}
