#!/usr/bin/env python3
"""Generates Models/SiteAreaCatalog.swift from the mounting-area SVG assets.

Reads outputs/<bodytype>/{front,rear}/<region>.svg (single-path region shapes
in the same viewBox as the matching body silhouette) and emits Swift path
data keyed by body type and site ID.

Rear views use standard anatomy (wearer's left on the viewer's left), but the
asset file names are mirror-consistent with the front (\"left\" always sits on
the viewer's right), so rear file names have left/right SWAPPED relative to
the site they represent. This script performs that remap.

Usage: python3 scripts/generate_site_areas.py [source-dir]
Defaults to the vendored sources in assets-src/site-areas, so the catalog is
reproducible from the repository alone.
"""
import re
import sys
from pathlib import Path

BODY_TYPES = ["neutral", "woman", "man"]
VIEWS = ["front", "rear"]

# file stem -> site ID (identity on the front; left/right swapped on the rear)
def site_id(view: str, stem: str) -> str:
    if view == "front":
        return stem
    if stem.endswith("-left"):
        return stem[: -len("-left")] + "-right"
    if stem.endswith("-right"):
        return stem[: -len("-right")] + "-left"
    raise ValueError(f"unexpected file name: {stem}")

def main(outputs: Path) -> None:
    entries = {}
    for body in BODY_TYPES:
        sites = {}
        for view in VIEWS:
            for svg in sorted((outputs / body / view).glob("*.svg")):
                src = svg.read_text()
                match = re.search(r'viewBox="0 0 (\d+) (\d+)"', src)
                width, height = match.groups()
                d = re.search(r'\sd="([^"]+)"', src, re.S).group(1)
                d = " ".join(d.split())
                sites[site_id(view, svg.stem)] = (width, height, d)
        if sites:
            entries[body] = sites

    lines = [
        "// Generated by scripts/generate_site_areas.py — do not edit by hand.",
        "// Source: mounting-area SVGs (one closed path per site, in the same",
        "// viewBox as the matching body silhouette). Rear file names are",
        "// left/right swapped relative to the wearer; the generator remaps them.",
        "import CoreGraphics",
        "",
        "struct SiteArea: Hashable {",
        "    let viewBoxWidth: CGFloat",
        "    let viewBoxHeight: CGFloat",
        "    let pathData: String",
        "}",
        "",
        "enum SiteAreaCatalog {",
        "    static func area(for siteID: String, bodyType: BodyType) -> SiteArea? {",
        "        areas[bodyType.rawValue]?[siteID]",
        "    }",
        "",
        "    static let areas: [String: [String: SiteArea]] = [",
    ]
    for body, sites in sorted(entries.items()):
        lines.append(f'        "{body}": [')
        for sid, (w, h, d) in sorted(sites.items()):
            lines.append(
                f'            "{sid}": SiteArea(viewBoxWidth: {w}, viewBoxHeight: {h}, pathData: "{d}"),'
            )
        lines.append("        ],")
    lines += ["    ]", "}", ""]

    dest = Path(__file__).resolve().parent.parent / "InsulinPumpSiteJournal/Models/SiteAreaCatalog.swift"
    dest.write_text("\n".join(lines))
    counts = {b: len(s) for b, s in entries.items()}
    print(f"wrote {dest.name}: {counts}")

if __name__ == "__main__":
    default = Path(__file__).resolve().parent.parent / "assets-src/site-areas"
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else default)
